-- seleciona os médicos e seu supervisores (DEREF)
SELECT
    M.CRM                       AS MEDICO_CRM,
    M.DESCRICAO_BASICA()        AS MEDICO_DESC,
    M.IDADE()                   AS MEDICO_IDADE,
    DEREF(M.SUPERVISOR).CPF     AS SUPERVISOR_CPF,
    DEREF(M.SUPERVISOR).CRM     AS SUPERVISOR_CRM,
    DEREF(M.SUPERVISOR).NOME    AS SUPERVISOR_NOME,
    DEREF(M.SUPERVISOR).IDADE() AS SUPERVISOR_IDADE
FROM
    TB_MEDICO M;

-- RES:
-- MEDICO_CPF MEDICO_CRM MEDICO_NOME MEDICO_IDADE SUPERVISOR_CPF SUPERVISOR_CRM SUPERVISOR_NOME SUPERVISOR_IDADE
-- 999999 424243 Maria Leticia 23 12345678901 424242 Jonescleison da Silva 23
-- 999997 424247 Maria Glória 22 999999 424243 Maria Leticia 23
-- 999996 424500 José Lucas 22 999999 424243 Maria Leticia 23
-- 12345678901 424242 JONESCLEISON DA SILVA 23 - - - -
-- 12345678902 424245 NEYMAR DA SILVA 23 - - - -



-- seleciona os médicos com especialidade em anestesista e seus supervisores (consulta VARRAY)
SELECT
    M.CPF                    AS MEDICO_CPF,
    M.CRM                    AS MEDICO_CRM,
    M.NOME                   AS MEDICO_NOME,
    DEREF(M.SUPERVISOR).CPF  AS SUPERVISOR_CPF,
    DEREF(M.SUPERVISOR).CRM  AS SUPERVISOR_CRM,
    DEREF(M.SUPERVISOR).NOME AS SUPERVISOR_NOME
FROM
    TB_MEDICO M,
    TABLE(M.ESPECIALIDADES) E
WHERE
    E.ESPECIALIDADE = 'Anestesista';         

-- RES:
--MEDICO_CPF MEDICO_CRM MEDICO_NOME SUPERVISOR_CPF SUPERVISOR_CRM SUPERVISOR_NOME
--999996 424500 José Lucas 999999 424243 Maria Leticia
--999997 424247 Maria Glória 999999 424243 Maria Leticia



-- seleciona os funcionários que trabalham na enfermaria (consulta NESTED TABLE)
SELECT
    DISTINCT DEREF(FT.FUNCIONARIO).NUM_CLT AS FUNCIONARIO_CLT,
    DEREF(FT.FUNCIONARIO).NOME    AS FUNCIONARIO_NOME,
    FTL.NOME                      AS SETOR
FROM
    FUNCIONARIO_TRABALHA FT,
    TABLE(FT.LISTA_SETOR) FTL
WHERE
    FTL.NOME = 'Enfermaria';                    

-- RES:
-- FUNCIONARIO_CLT FUNCIONARIO_NOME SETOR
-- 1400004 José Lucas Enfermaria
-- 1400003 Maria Glória Enfermaria



-- lista os Acompanhantes de um paciente (REF)
SELECT
    A.ACOMPANHANTENOME() AS ACOMPANHANTE_NOME
FROM
    TB_ACOMPANHANTE A,
    TB_PACIENTE     P
WHERE
    A.PACIENTE = REF(P)
    AND P.CPF = '34565467100';

-- RES
-- ACOMPANHANTE_NOME
-- JOANA CLEISON

SELECT
    A.ACOMPANHANTENOME() AS ACOMPANHANTE_NOME
FROM
    TB_ACOMPANHANTE A,
    TB_PACIENTE     P
WHERE
    A.PACIENTE = REF(P)
    AND P.CPF = '34565467809';

-- RES:
-- ACOMPANHANTE_NOME
-- PAULO DA SILVA
-- PAOLA DA SILVA



-- lista Pacientes
SELECT
    P.DESCRICAO_BASICA() AS PACIENTE
FROM
    TB_PACIENTE P;

-- RES:
-- PACIENTE
-- NOME: JONES CLEISON, CPF: 34565467100, TIPO SANGUÍNEO: AB+
-- NOME: BIANCA DA SILVA, CPF: 34565467809, TIPO SANGUÍNEO: AB+



-- setores das salas após internação
SELECT
    SETOR.NOME   AS SETOR,
    SALAA.NUMERO AS SALA
FROM
    TB_SETOR SETOR,
    TB_SALA  SALAA
WHERE
    SALAA.SETOR = REF(SETOR)
    AND DEREF(REF(SALAA)) > DEREF((
        SELECT
            REF(SALAB)
        FROM
            TB_SALA SALAB
        WHERE
            DEREF(SALAB.SETOR).NOME = 'internação'
    ));

-- RES:
-- SETOR SALA
-- CIRURGIA 10
-- RADIOLOGIA 6
-- ENFERMARIA 7
-- RECEPÇÃO 8
-- GERÊNCIA 9



-- salario dos funcionarios

SELECT
    F.NOME,
    F.CPF,
    F.SALARIO,
    F.BONIFICACAO,
    F.PAGAMENTO() AS PAGAMENTO_
FROM
    TB_MEDICO     F
UNION
SELECT
    F.NOME,
    F.CPF,
    F.SALARIO,
    F.BONIFICACAO,
    F.PAGAMENTO() AS PAGAMENTO_
FROM
    TB_ENFERMEIRO F
UNION
SELECT
    F.NOME,
    F.CPF,
    F.SALARIO,
    F.BONIFICACAO,
    F.PAGAMENTO() AS PAGAMENTO_
FROM
    TB_ATENDENTE  F;

-- RES:
-- NOME CPF SALARIO BONIFICACAO PAGAMENTO_
-- JONESCLEISON DA SILVA 12345678901 14020 - 14020
-- JOSÉ LUCAS 999996 14020 - 14020
-- JUANILDA DE ALENCAR 11111111101 3000 100 3100
-- MARIA GLÓRIA 999997 14020 - 14020
-- MARIA LETICIA 999999 14020 - 14020
-- NEYMAR DA SILVA 12345678902 14021 - 14021
-- PELÉ ROCHA AMOEDO 24335573610 9000 - 11000