-- seleciona os médicos e seu supervisores (DEREF)
SELECT
    M.CPF                    AS MEDICO_CPF,
    M.CRM                    AS MEDICO_CRM,
    M.NOME                   AS MEDICO_NOME,
    DEREF(M.SUPERVISOR).CPF  AS SUPERVISOR_CPF,
    DEREF(M.SUPERVISOR).CRM  AS SUPERVISOR_CRM,
    DEREF(M.SUPERVISOR).NOME AS SUPERVISOR_NOME
FROM
    TB_MEDICO M;

-- RES:
-- MEDICO_CPF MEDICO_CRM MEDICO_NOME SUPERVISOR_CPF SUPERVISOR_CRM SUPERVISOR_NOME
-- 12345678901 424242 JONESCLEISON DA SILVA - - -
-- 12345678902 424245 NEYMAR DA SILVA - - -
-- 999996 424500 JOSÉ LUCAS 999999 424243 MARIA LETICIA
-- 999999 424243 Maria Leticia 12345678901 424242 Jonescleison da silva
-- 999997 424247 Maria Glória 999999 424243 Maria Leticia



-- seleciona os médicos com especialidade em anestesista e seus supervisores (consulta VARRAY)
SELECT
    M.CPF                    AS MEDICO_CPF,
    M.CRM                    AS MEDICO_CRM,
    M.NOME                   AS MEDICO_NOME,
    DEREF(M.SUPERVISOR).CPF  AS SUPERVISOR_CPF,
    DEREF(M.SUPERVISOR).CRM  AS SUPERVISOR_CRM,
    DEREF(M.SUPERVISOR).NOME AS SUPERVISOR_NOME
FROM
    TB_MEDICO M,
    TABLE(M.ESPECIALIDADES) E
WHERE
    E.ESPECIALIDADE = 'anestesista';         

-- RES:
--MEDICO_CPF MEDICO_CRM MEDICO_NOME SUPERVISOR_CPF SUPERVISOR_CRM SUPERVISOR_NOME
--999996 424500 José Lucas 999999 424243 Maria Leticia
--999997 424247 Maria Glória 999999 424243 Maria Leticia



-- seleciona os funcionários que trabalham na enfermaria (consulta NESTED TABLE)
SELECT
    DISTINCT DEREF(FT.FUNCIONARIO).NUM_CLT AS FUNCIONARIO_CLT,
    DEREF(FT.FUNCIONARIO).NOME    AS FUNCIONARIO_NOME,
    FTL.NOME                      AS SETOR
FROM
    FUNCIONARIO_TRABALHA FT,
    TABLE(FT.LISTA_SETOR) FTL
WHERE
    FTL.NOME = 'Enfermaria';                    

-- RES:
-- FUNCIONARIO_CLT FUNCIONARIO_NOME SETOR
-- 1400004 José Lucas Enfermaria
-- 1400003 Maria Glória Enfermaria



-- lista os Acompanhantes de um paciente (REF)
SELECT
    A.ACOMPANHANTENOME() AS ACOMPANHANTE_NOME
FROM
    TB_ACOMPANHANTE A,
    TB_PACIENTE     P
WHERE
    A.PACIENTE = REF(P)
    AND P.CPF = '34565467100';

-- RES
-- ACOMPANHANTE_NOME
-- JOANA CLEISON

SELECT
    A.ACOMPANHANTENOME() AS ACOMPANHANTE_NOME
FROM
    TB_ACOMPANHANTE A,
    TB_PACIENTE     P
WHERE
    A.PACIENTE = REF(P)
    AND P.CPF = '34565467809';

-- RES:
-- ACOMPANHANTE_NOME
-- PAULO DA SILVA
-- PAOLA DA SILVA