-- setor(1)
INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'triagem'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'consultório'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'nebulização'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'medicação'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'internação'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'Radiologia'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'Enfermaria'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'Recepção'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'Gerência'
);

INSERT INTO TB_SETOR(
    NOME
) VALUES(
    'Cirurgia'
);

--sala (2)

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    1,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'triagem')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    10,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'Cirurgia')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    2,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'consultório')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    3,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'nebulização')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    4,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'medicação')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    5,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'internação')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    6,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'Radiologia')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    7,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'Enfermaria')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    8,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'Recepção')
);

INSERT INTO TB_SALA (
    NUMERO,
    SETOR
) VALUES (
    9,
    (SELECT REF(S) FROM TB_SETOR S WHERE NOME = 'Gerência')
);

-- Médicos

INSERT INTO TB_MEDICO VALUES (
    TP_MEDICO( '12345678901', TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'), 'Jonescleison da Silva', DATE '2001-05-04', TP_FONES(TP_FONE(993886666)), 14020, DATE '2024-01-28', 1400000, NULL, '424242', TP_ESPECIALIDADES_MEDICO(TP_ESPECIALIDADE_MEDICO('Cirurgião Cardíaco')), NULL )
);

INSERT INTO TB_MEDICO VALUES (
    TP_MEDICO( '12345678902', TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'), 'Neymar da Silva', DATE '2001-05-03', TP_FONES(TP_FONE(993886670)), 14021, DATE '2024-01-27', 1400002, NULL, '424245', TP_ESPECIALIDADES_MEDICO(TP_ESPECIALIDADE_MEDICO('Cirurgião Cardíaco')), NULL )
);

-- Consulta aninhada com REF
INSERT INTO TB_MEDICO VALUES (
    TP_MEDICO( '999999', TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'), 'Maria Leticia', DATE '2001-05-04', TP_FONES(TP_FONE(993886667)), 14020, DATE '2024-01-28', 1400001, NULL, '424243', TP_ESPECIALIDADES_MEDICO(TP_ESPECIALIDADE_MEDICO('Cirurgião Cardíaco')), (SELECT REF(M) FROM TB_MEDICO M WHERE M.CPF = '12345678901') )
);

INSERT INTO TB_MEDICO VALUES (
    TP_MEDICO( '999997', TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'), 'Maria Glória', DATE '2002-05-04', TP_FONES(TP_FONE(993886667)), 14020, DATE '2023-01-28', 1400003, NULL, '424247', TP_ESPECIALIDADES_MEDICO(TP_ESPECIALIDADE_MEDICO('Anestesista')), (SELECT REF(M) FROM TB_MEDICO M WHERE M.CPF = '999999') )
);

INSERT INTO TB_MEDICO VALUES (
    TP_MEDICO('999996', TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'), 'José Lucas', DATE '2002-05-04', TP_FONES(TP_FONE(993886666)), 14020, DATE '2023-01-28', 1400004, NULL, '424500', TP_ESPECIALIDADES_MEDICO(TP_ESPECIALIDADE_MEDICO('Anestesista')), (SELECT REF(M) FROM TB_MEDICO M WHERE M.CPF = '999999') )
);

INSERT INTO FUNCIONARIO_TRABALHA VALUES (
    (SELECT REF(M) FROM TB_MEDICO M WHERE M.CPF = '999996'),
    TP_NT_SETOR(TP_SETOR('Cirurgia'), TP_SETOR('Enfermaria'))
);

INSERT INTO FUNCIONARIO_TRABALHA VALUES (
    (SELECT REF(M) FROM TB_MEDICO M WHERE M.CPF = '999999'),
    TP_NT_SETOR(TP_SETOR('Cirurgia'))
);

INSERT INTO FUNCIONARIO_TRABALHA VALUES (
    (SELECT REF(M) FROM TB_MEDICO M WHERE M.CPF = '999997'),
    TP_NT_SETOR(TP_SETOR('Enfermaria'))
);

-- Pacientes e Acompanhantes
INSERT INTO TB_PACIENTE (
    CPF,
    ENDERECO, -- TP_ENDERECO
    NOME,
    DATA_DE_NASCIMENTO,
    TELEFONES, -- TP_FONES
    PRESSAO_ARTERIAL,
    PESO,
    ALTURA,
    TIPO_SANGUINEO,
    HISTORICO_MEDICO -- ref TP_HISTORICO_MEDICO
) VALUES (
    '34565467809',
    TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'),
    'Bianca da Silva',
    DATE '1995-06-24',
    TP_FONES(TP_FONE(81993086976)),
    '13/8',
    70,
    180,
    'AB+',
    NULL
);

INSERT INTO TB_ACOMPANHANTE(
    PACIENTE, -- REF TP_PACIENTE
    NOME,
    GRAU_DE_PARENTESCO,
    CPF
) VALUES (
    (SELECT REF(P) FROM TB_PACIENTE P WHERE P.CPF = '34565467809'),
    'Paulo da Silva',
    1,
    '34565467808'
);

INSERT INTO TB_ACOMPANHANTE(
    PACIENTE, -- REF TP_PACIENTE
    NOME,
    GRAU_DE_PARENTESCO,
    CPF
) VALUES (
    (SELECT REF(P) FROM TB_PACIENTE P WHERE P.CPF = '34565467809'),
    'Paola da Silva',
    1,
    '34565467807'
);

INSERT INTO TB_PACIENTE (
    CPF,
    ENDERECO, -- TP_ENDERECO
    NOME,
    DATA_DE_NASCIMENTO,
    TELEFONES, -- TP_FONES
    PRESSAO_ARTERIAL,
    PESO,
    ALTURA,
    TIPO_SANGUINEO,
    HISTORICO_MEDICO -- ref TP_HISTORICO_MEDICO
) VALUES (
    '34565467100',
    TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'),
    'Jones Cleison',
    DATE '1995-06-24',
    TP_FONES(TP_FONE(81993086976)),
    '13/8',
    70,
    180,
    'AB+',
    NULL
);

INSERT INTO TB_ACOMPANHANTE(
    PACIENTE, -- REF TP_PACIENTE
    NOME,
    GRAU_DE_PARENTESCO,
    CPF
) VALUES (
    (SELECT REF(P) FROM TB_PACIENTE P WHERE P.CPF = '34565467100'),
    'Joana Cleison',
    1,
    '34565467806'
);

-- Atendentes (constructor)
INSERT INTO TB_ATENDENTE VALUES (
    TP_ATENDENTE(TP_FUNCIONARIO('11111111101', TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'), 'Juanilda de Alencar', DATE '1991-01-01', TP_FONES(TP_FONE(993886650)), 3000, DATE '2023-12-01', 456789, 100 ))
);

-- enfermeiros
INSERT INTO TB_ENFERMEIRO (
    CPF,
    ENDERECO, -- TP_ENDERECO
    NOME,
    DATA_DE_NASCIMENTO,
    TELEFONES, -- TP_FONES
    SALARIO,
    DATA_DE_ADMISSAO,
    NUM_CLT,
    COREN,
    SUPERVISOR
) VALUES (
    '24335573610',
    TP_ENDERECO('52050642', 'rua do limão', 600, 'limoeiro', 'São Paulo'),
    'Pelé Rocha Amoedo',
    DATE '2000-05-05',
    TP_FONES(TP_FONE(993886640), TP_FONE(993886630)),
    9000,
    DATE '2024-01-01',
    4567,
    891011,
    NULL
)