-- setor (1)
CREATE TABLE TB_SETOR OF TP_SETOR (
    NOME PRIMARY KEY
);

/

-- sala(2)

CREATE TABLE TB_SALA OF TP_SALA (
    SETOR SCOPE IS TB_SETOR
);

/

-- historico medico (4)

CREATE TABLE TB_HISTORICO_MEDICO OF TP_HISTORICO_MEDICO (
    ID PRIMARY KEY
);

/

-- paciente (5)

CREATE TABLE TB_PACIENTE OF TP_PACIENTE (
    CPF PRIMARY KEY,
    HISTORICO_MEDICO SCOPE IS TB_HISTORICO_MEDICO,
    CONSTRAINT PACIENTE_CHECKPESO CHECK (PESO > 0),
    CONSTRAINT PACIENTE_CHECKALTURA CHECK (ALTURA > 0),
    CONSTRAINT PACIENTE_CHECKTIPOSANGUINEO CHECK ( TIPO_SANGUINEO = 'A+' OR TIPO_SANGUINEO = 'A-' OR TIPO_SANGUINEO = 'B+' OR TIPO_SANGUINEO = 'B-' OR TIPO_SANGUINEO = 'AB+' OR TIPO_SANGUINEO = 'AB-' OR TIPO_SANGUINEO = 'O+' OR TIPO_SANGUINEO = 'O-' )
);

/

-- medico (6)
CREATE TABLE TB_MEDICO OF TP_MEDICO (
    CPF PRIMARY KEY,
    NUM_CLT UNIQUE,
    CRM UNIQUE,
    SUPERVISOR SCOPE IS TB_MEDICO
);

/

-- enfermeiro (7)

CREATE TABLE TB_ENFERMEIRO OF TP_ENFERMEIRO (
    CPF PRIMARY KEY,
    NUM_CLT UNIQUE,
    COREN UNIQUE,
    SUPERVISOR SCOPE IS TB_ENFERMEIRO
);

/

-- acompanhante (8)
CREATE TABLE TB_ACOMPANHANTE OF TP_ACOMPANHANTE (
    CPF PRIMARY KEY,
    PACIENTE WITH ROWID REFERENCES TB_PACIENTE
);

/

CREATE TABLE TB_ATENDENTE OF TP_ATENDENTE (
    CPF PRIMARY KEY,
    NUM_CLT UNIQUE
);

/

-- trabalha(10)

CREATE OR REPLACE TYPE TP_NT_SETOR AS
    TABLE OF TP_SETOR;
/

CREATE TABLE FUNCIONARIO_TRABALHA (
    FUNCIONARIO REF TP_FUNCIONARIO,
    LISTA_SETOR TP_NT_SETOR
) NESTED TABLE LISTA_SETOR STORE AS TB_LISTA_SETOR;

/

-- diagnostico(13)
CREATE TABLE TB_DIAGNOSTICO OF TP_DIAGNOSTICO (
    MEDICO SCOPE IS TB_MEDICO,
    PACIENTE SCOPE IS TB_PACIENTE
);

/

-- diagnostico(14)
CREATE TABLE TB_RECEITA OF TP_RECEITA (
    MEDICO SCOPE IS TB_MEDICO,
    PACIENTE SCOPE IS TB_PACIENTE
);

/

-- consulta(12)

CREATE TABLE TB_CONSULTA OF TP_CONSULTA (
    SALA SCOPE IS TB_SALA,
    MEDICO SCOPE IS TB_MEDICO,
    PACIENTE SCOPE IS TB_PACIENTE,
    RECEITA SCOPE IS TB_RECEITA,
    DIAGNOSTICO SCOPE IS TB_DIAGNOSTICO
);

/

-- enfermeiro responsável(15)
CREATE TABLE TB_ENFERMEIRO_RESPONSABEL OF TP_ENFERMEIRO_RESPONSAVEL (
    ENFERMEIRO SCOPE IS TB_ENFERMEIRO,
    PACIENTE SCOPE IS TB_PACIENTE
);

/

-- medico responsável(16)
CREATE TABLE TB_MEDICO_RESPONSAVEL OF TP_MEDICO_RESPONSAVEL(
    MEDICO SCOPE IS TB_MEDICO,
    ENFERMEIRO_PACIENTE SCOPE IS TB_ENFERMEIRO_RESPONSABEL
);